import * as vscode from "vscode";
import { exec } from "child_process";
import * as fs from "fs";
import * as path from "path";

export async function activate(context: vscode.ExtensionContext) {
  console.log("✅ PR Name Fixer activated");

  // Check for Git repository on startup
  const workspacePath = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (workspacePath && fs.existsSync(path.join(workspacePath, ".git"))) {
    const ghReady = await checkGhAuth();
    if (ghReady) {
      installPrePushHook(workspacePath);
      vscode.window.showInformationMessage("✅ PR Name Fixer: pre-push hook installed for this repository.");
    }
  } else if (workspacePath) {
    vscode.window.showWarningMessage("No Git repository detected in the workspace.");
  } else {
    vscode.window.showErrorMessage("No workspace folder detected.");
  }

  const disposable = vscode.commands.registerCommand("pr-name-fixer.executeTask", async () => {
    const workspacePath = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    if (workspacePath && fs.existsSync(path.join(workspacePath, ".git"))) {
      const ghReady = await checkGhAuth();
      if (ghReady) {
        installPrePushHook(workspacePath);
      }
    } else if (workspacePath) {
      vscode.window.showWarningMessage("No Git repository detected in the workspace.");
    } else {
      vscode.window.showErrorMessage("No workspace folder detected.");
    }
  });

  context.subscriptions.push(disposable);
}

async function checkGhAuth(): Promise<boolean> {
  const ghInstalled = await new Promise<boolean>((resolve) => {
    exec("gh --version", (err) => resolve(!err));
  });

  if (!ghInstalled) {
    const choice = await vscode.window.showWarningMessage(
      "GitHub CLI (gh) is not installed. Required to fix PR title.",
      "Install",
      "Cancel"
    );
    if (choice === "Install") {
      const terminal = vscode.window.createTerminal("Install GitHub CLI");
      terminal.show();
      terminal.sendText("brew install gh");
    }
    return false;
  }

  const isAuthenticated = await new Promise<boolean>((resolve) => {
    exec("gh auth status", (err, stdout) =>
      resolve(!err && stdout.includes("Logged in to github.com"))
    );
  });

  if (!isAuthenticated) {
    const choice = await vscode.window.showInformationMessage(
      "You are not authenticated with GitHub CLI. Log in now?",
      "Yes",
      "No"
    );
    if (choice === "Yes") {
      const terminal = vscode.window.createTerminal("GitHub Auth");
      terminal.show();
      terminal.sendText("gh auth login");
    }
    return false;
  }

  return true;
}

const fixPRTitleScript = `
BASE_BRANCH="main"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

PR_NUMBER=$(gh pr list --head "$CURRENT_BRANCH" --state open --json number -q '.[0].number')

if [[ -z "$PR_NUMBER" || "$PR_NUMBER" == "null" ]]; then
  echo "❌ No open PR found for branch: $CURRENT_BRANCH"
  exit 0
fi

PR_TITLE=$(gh pr view "$PR_NUMBER" --json title -q '.title')
TITLE_LOWER=$(echo "$PR_TITLE" | tr '[:upper:]' '[:lower:]')

if [[ "$TITLE_LOWER" =~ ^(feature|hotfix|bugfix|release)/[0-9]+ ]]; then
  echo "✅ PR title already follows convention. Skipping."
  exit 0
fi

NEW_TITLE="\${CURRENT_BRANCH//_/ }"
echo "🛠️ Updating PR #$PR_NUMBER title to: $NEW_TITLE"
gh pr edit "$PR_NUMBER" --title "$NEW_TITLE"
`;

function installPrePushHook(workspacePath: string) {
  const hookDir = path.join(workspacePath, ".git", "hooks");
  const hookPath = path.join(hookDir, "pre-push");

  if (!fs.existsSync(hookDir)) {
    vscode.window.showWarningMessage("Could not find .git/hooks directory.");
    return;
  }

  const existing = fs.existsSync(hookPath) ? fs.readFileSync(hookPath, "utf8") : "";

  if (existing.includes("gh pr edit")) {
    console.log("⚠️ pre-push hook already contains PR Name Fixer logic. Skipping installation.");
    return;
  }

  const scriptToWrite = `#!/bin/bash
# Auto-generated by PR Name Fixer VS Code Extension

${fixPRTitleScript}
`;

  try {
    fs.writeFileSync(hookPath, scriptToWrite);
    fs.chmodSync(hookPath, 0o755);
    vscode.window.showInformationMessage("✅ PR Name Fixer: pre-push hook installed.");
  } catch (err) {
    console.error("❌ Failed to write pre-push hook:", err);
  }
}

export function deactivate() {}